#! /bin/sh

asusctl profile -P Balanced
xset r rate 300 50
xsetroot -Bibata-Modern-Classic left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &


displayport="$(xrandr --query | grep -o "DP-. connected" | cut -d " " -f 1)"

if [[ $(xrandr -q | grep "HDMI-0 connected") ]]; then
    displayport = "eDP"
fi
if [[ $(xrandr -q | grep "HDMI-0 connected") ]]; then
    xrandr --output HDMI-0 --mode 2560x1440 --rate 144 --primary 
    
    xrandr --output $displayport --mode 2560x1440 --rate 165
 
    bspc wm -O HDMI-0
    
    bspc monitor HDMI-0 -d 1 2 3 4 5
    bspc monitor $displayport -d 6 7 8 9


else  
    xrandr --output $displayport --mode 2560x1440 --rate 165
    
    bspc monitor $displayport -d 1 2 3 4 5 6 7 8 9
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on
bspc rule -a kitty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a obs desktop='^9'
bspc rule -a yandex-music desktop='^8'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a code-oss desktop='^4'
bspc rule -a Zoom desktop='^7'
#bspc rule -a LMStudio desktop='^6'

bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"



bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize


sxhkd &
picom --config ~/.config/picom/picom.conf &

if [[ $(xrandr -q | grep "HDMI-0 connected") ]]; then
    polybar main &
    #eww open bar -c $HOME/.config/eww/bar --screen 0
fi
polybar laptop &
#eww open bar -c $HOME/.config/eww/bar1 --screen 1

nitrogen --restore &
dunst &
